# languages.py
LANGS = {
    'en': {
        'main_menu': [
            ["🚗 Add Car", "🔍 Browse Cars"],
            ["🗂️ My Cars", "📊 Stats"],
            ["ℹ️ Help", "🌐 Language"]
        ],
        'cancel_menu': [
            ["❌ Cancel", "🏠 Main Menu"]
        ],
        'explore_menu': [
            ["💵 Under $10K", "💰 Under $20K"],
            ["💎 Under $30K", "📋 All Cars"],
            ["🏠 Main Menu"]
        ],
        'welcome': "<b>🎉 Welcome to Car Marketplace!</b>\n\n🚗 Your perfect platform to buy and sell cars\n\n<b>What would you like to do?</b>\n• 🚗 <b>Add Car</b> - List your car for sale\n• 🔍 <b>Browse Cars</b> - Find your perfect car\n• 🗂️ <b>My Cars</b> - View and manage your listings\n• 📊 <b>Stats</b> - Market information\n• ℹ️ <b>Help</b> - Usage guide\n• 🌐 <b>Language</b> - Change language\n\n💡 <b>Tip:</b> Access commands from the menu below or the menu button 📝",
        'help': "<b>📖 Bot Usage Guide</b>\n\n<b>🚗 To add a car:</b>\n1️⃣ Tap <b>Add Car</b>\n2️⃣ Enter car details step by step\n3️⃣ Send a clear photo of the car\n\n<b>🔍 To find a car:</b>\n1️⃣ Tap <b>Browse Cars</b>\n2️⃣ Choose your price range\n3️⃣ Browse results and contact sellers\n\n<b>🗂️ To manage your cars:</b>\n1️⃣ Tap <b>My Cars</b>\n2️⃣ View your listings\n3️⃣ Delete any listing with the button\n\n<b>💡 Important Tips:</b>\n• Use the persistent menu below\n• Cancel any operation with <b>Cancel</b>\n• Prices in US Dollars\n\n<b>🆘 Need help?</b>\nContact: <b>jalalweez@gmail.com</b>",
        'stats': "<b>📊 Car Market Statistics</b>\n\n🚗 <b>Total Cars:</b> <b>{total}</b>\n\n<b>Price Distribution:</b>\n💵 Under $10K: {under_10k} cars\n💰 Under $20K: {under_20k} cars\n💎 Under $30K: {under_30k} cars\n\n📈 Market is active and updated daily!",
        'add_step1': "<b>🚘 Step 1 of 8</b>\n\nEnter car model:\n<i>Example: Toyota Corolla or Honda Civic</i>",
        'add_step2': "<b>📅 Step 2 of 8</b>\n\nEnter year of manufacture:\n<i>Example: 2020 or 2018</i>",
        'add_step2_invalid_format': "<b>⚠️ Please enter a valid year (4 digits)</b>\n<i>Example: 2020</i>",
        'add_step2_invalid_range': "<b>⚠️ Year must be between 1990 and 2025</b>",
        'add_step3': "<b>💰 Step 3 of 8</b>\n\nEnter price in US Dollars:\n<i>Example: 15000 or 25000</i>",
        'add_step3_invalid': "<b>⚠️ Please enter a valid price number</b>\n<i>Example: 15000 or 25000</i>",
        'add_step4': "<b>🛣️ Step 4 of 8</b>\n\nEnter mileage:\n<i>Example: 45000 or 120000</i>",
        'add_step4_invalid': "<b>⚠️ Please enter a valid mileage number (0 or positive)</b>\n<i>Example: 45000</i>",
        'add_step5': "<b>📍 Step 5 of 8</b>\n\nEnter location:\n<i>Example: Miami, FL or New York, NY</i>",
        'add_step6': "<b>⭐ Step 6 of 8</b>\n\nEnter condition rating (1-10):\n<i>Example: 8 for good condition</i>",
        'add_step6_invalid': "<b>⚠️ Please enter a valid rating between 1 and 10</b>\n<i>Example: 8</i>",
        'add_step7': "<b>📞 Step 7 of 8</b>\n\nEnter phone number:\n<i>Example: +1-555-123-4567 or 5551234567</i>",
        'add_step8': "<b>📸 Step 8 of 8 (Final)</b>\n\nSend a clear photo of the car:\n• Photo must be clear\n• Exterior photo preferred\n• Avoid blurry photos",
        'add_image_invalid': "<b>⚠️ No photo received!</b>\nPlease send one photo 📸",
        'add_success': "<b>✅ Your listing is live!</b>\n\n<b>🆔 Listing ID:</b> <code>{car_id}</code>\n<b>🚘 Model:</b> {model}\n<b>📅 Year:</b> {year}\n<b>💰 Price:</b> ${price:,.0f}\n<b>🛣️ Miles:</b> {miles:,}\n<b>📍 Location:</b> {location}\n<b>⭐ Condition:</b> {condition}/10\n<b>📞 Phone:</b> <code>{phone}</code>\n\n🎉 Your ad is now visible to everyone!\n📱 Buyers will contact you soon",
        'cancelled': "<b>❌ Operation cancelled</b>\n\n🏠 Back to main menu",
        'explore': "<b>🔍 Browse Available Cars</b>\n\nChoose your price range:\n💵 Under $10K\n💰 Under $20K\n💎 Under $30K\n📋 All available cars",
        'results_header': "<b>🔍 Search Results: {filter_name}</b>\n<b>📊 Results:</b> {count} cars\n\n⬇️ Showing cars...",
        'no_cars': "<b>🚫 No cars available</b>\n\n<b>Filter:</b> {filter_name}\nTry another filter or list your car! 🚗",
        'end_results': "<b>✅ End of results</b>\n\nChoose another search or return to main menu 🏠",
        'my_cars_header': "<b>🗂️ Your Listings: {count}</b>\n\n⬇️ Showing your cars...",
        'no_listings': "<b>🚫 You have no active listings</b>\n\n🚗 Add a new car from the menu!",
        'my_cars_end': "<b>✅ End of your listings</b>\n\n🏠 Back to main menu",
        'year_label': "📅 Year:",
        'price_label': "💰 Price:",
        'miles_label': "🛣️ Miles:",
        'location_label': "📍 Location:",
        'condition_label': "⭐ Condition:",
        'phone_label': "📞 Phone:",
        'posted_label': "🕐 Posted:",
        'contact_tip': "💡 Tap buttons below to contact seller",
        'manage_tip': "💡 Manage your listing below",
        'copy_phone': "📞 Copy Phone",
        'message_seller': "✉️ Message Seller",
        'delete': "🗑️ Delete",
        'yes_delete': "✅ Yes, Delete",
        'no_delete': "❌ No",
        'phone_copied': "📞 <b>{phone}</b>\n\n✅ Phone copied to clipboard!\n💡 Long press to copy again",
        'deletion_cancelled': "❌ Deletion cancelled",
        'listing_deleted': "✅ Listing deleted!",
        'delete_failed': "⚠️ Could not delete - not found or not yours",
        'listing_deleted_caption': "🚫 This listing has been deleted",
        'under_10k': "Under $10,000",
        'under_20k': "Under $20,000",
        'under_30k': "Under $30,000",
        'all_cars': "All Cars",
        'language_changed': "<b>✅ Language changed to {lang}</b>",
        'choose_language': "<b>🌐 Choose Your Language / اختر لغتك / Choisissez votre langue</b>"
    },
    'ar': {
        'main_menu': [
            ["🚗 إضافة سيارة", "🔍 تصفح السيارات"],
            ["🗂️ سياراتي", "📊 الإحصائيات"],
            ["ℹ️ المساعدة", "🌐 اللغة"]
        ],
        'cancel_menu': [
            ["❌ إلغاء", "🏠 القائمة الرئيسية"]
        ],
        'explore_menu': [
            ["💵 أقل من $10K", "💰 أقل من $20K"],
            ["💎 أقل من $30K", "📋 جميع السيارات"],
            ["🏠 القائمة الرئيسية"]
        ],
        'welcome': "<b>🎉 مرحبا بك في سوق السيارات!</b>\n\n🚗 منصتك المثالية للبيع والشراء السيارات\n\n<b>ماذا تريد أن تفعل؟</b>\n• 🚗 <b>إضافة سيارة</b> - أدرج سيارتك للبيع\n• 🔍 <b>تصفح السيارات</b> - ابحث عن سيارتك المثالية\n• 🗂️ <b>سياراتي</b> - عرض وإدارة إعلاناتك\n• 📊 <b>الإحصائيات</b> - معلومات السوق\n• ℹ️ <b>المساعدة</b> - دليل الاستخدام\n• 🌐 <b>اللغة</b> - تغيير اللغة\n\n💡 <b>نصيحة:</b> الوصول إلى الأوامر من القائمة أدناه أو زر القائمة 📝",
        'help': "<b>📖 دليل استخدام البوت</b>\n\n<b>🚗 لإضافة سيارة:</b>\n1️⃣ اضغط <b>إضافة سيارة</b>\n2️⃣ أدخل تفاصيل السيارة خطوة بخطوة\n3️⃣ أرسل صورة واضحة للسيارة\n\n<b>🔍 للعثور على سيارة:</b>\n1️⃣ اضغط <b>تصفح السيارات</b>\n2️⃣ اختر نطاق السعر\n3️⃣ تصفح النتائج وتواصل مع البائعين\n\n<b>🗂️ لإدارة سياراتك:</b>\n1️⃣ اضغط <b>سياراتي</b>\n2️⃣ عرض إعلاناتك\n3️⃣ احذف أي إعلان بالزر\n\n<b>💡 نصائح مهمة:</b>\n• استخدم القائمة الثابتة أدناه\n• ألغ أي عملية بـ <b>إلغاء</b>\n• الأسعار بالدولار الأمريكي\n\n<b>🆘 تحتاج مساعدة؟</b>\nتواصل: <b>jalalweez@gmail.com</b>",
        'stats': "<b>📊 إحصائيات سوق السيارات</b>\n\n🚗 <b>إجمالي السيارات:</b> <b>{total}</b>\n\n<b>توزيع الأسعار:</b>\n💵 أقل من $10K: {under_10k} سيارة\n💰 أقل من $20K: {under_20k} سيارة\n💎 أقل من $30K: {under_30k} سيارة\n\n📈 السوق نشط ومحدث يومياً!",
        'add_step1': "<b>🚘 الخطوة 1 من 8</b>\n\nأدخل موديل السيارة:\n<i>مثال: تويوتا كورولا أو هوندا سيفيك</i>",
        'add_step2': "<b>📅 الخطوة 2 من 8</b>\n\nأدخل سنة التصنيع:\n<i>مثال: 2020 أو 2018</i>",
        'add_step2_invalid_format': "<b>⚠️ يرجى إدخال سنة صالحة (4 أرقام)</b>\n<i>مثال: 2020</i>",
        'add_step2_invalid_range': "<b>⚠️ السنة يجب أن تكون بين 1990 و 2025</b>",
        'add_step3': "<b>💰 الخطوة 3 من 8</b>\n\nأدخل السعر بالدولار الأمريكي:\n<i>مثال: 15000 أو 25000</i>",
        'add_step3_invalid': "<b>⚠️ يرجى إدخال رقم سعر صالح</b>\n<i>مثال: 15000 أو 25000</i>",
        'add_step4': "<b>🛣️ الخطوة 4 من 8</b>\n\nأدخل عدد الكيلومترات:\n<i>مثال: 45000 أو 120000</i>",
        'add_step4_invalid': "<b>⚠️ يرجى إدخال رقم كيلومترات صالح (0 أو إيجابي)</b>\n<i>مثال: 45000</i>",
        'add_step5': "<b>📍 الخطوة 5 من 8</b>\n\nأدخل الموقع:\n<i>مثال: ميامي، فلوريدا أو نيويورك، نيويورك</i>",
        'add_step6': "<b>⭐ الخطوة 6 من 8</b>\n\nأدخل تقييم الحالة (1-10):\n<i>مثال: 8 لحالة جيدة</i>",
        'add_step6_invalid': "<b>⚠️ يرجى إدخال تقييم صالح بين 1 و 10</b>\n<i>مثال: 8</i>",
        'add_step7': "<b>📞 الخطوة 7 من 8</b>\n\nأدخل رقم الهاتف:\n<i>مثال: +1-555-123-4567 أو 5551234567</i>",
        'add_step8': "<b>📸 الخطوة 8 من 8 (الأخيرة)</b>\n\nأرسل صورة واضحة للسيارة:\n• الصورة يجب أن تكون واضحة\n• صورة خارجية مفضلة\n• تجنب الصور الغامضة",
        'add_image_invalid': "<b>⚠️ لم يتم استلام صورة!</b>\nيرجى إرسال صورة واحدة 📸",
        'add_success': "<b>✅ إعلانك نشط!</b>\n\n<b>🆔 معرف الإعلان:</b> <code>{car_id}</code>\n<b>🚘 الموديل:</b> {model}\n<b>📅 السنة:</b> {year}\n<b>💰 السعر:</b> ${price:,.0f}\n<b>🛣️ الكيلومترات:</b> {miles:,}\n<b>📍 الموقع:</b> {location}\n<b>⭐ الحالة:</b> {condition}/10\n<b>📞 الهاتف:</b> <code>{phone}</code>\n\n🎉 إعلانك مرئي للجميع الآن!\n📱 سيتواصل المشترون معك قريبا",
        'cancelled': "<b>❌ تم إلغاء العملية</b>\n\n🏠 العودة إلى القائمة الرئيسية",
        'explore': "<b>🔍 تصفح السيارات المتاحة</b>\n\nاختر نطاق السعر:\n💵 أقل من $10K\n💰 أقل من $20K\n💎 أقل من $30K\n📋 جميع السيارات",
        'results_header': "<b>🔍 نتائج البحث: {filter_name}</b>\n<b>📊 النتائج:</b> {count} سيارة\n\n⬇️ عرض السيارات...",
        'no_cars': "<b>🚫 لا سيارات متاحة</b>\n\n<b>الفلتر:</b> {filter_name}\nجرب فلتر آخر أو أدرج سيارتك! 🚗",
        'end_results': "<b>✅ نهاية النتائج</b>\n\nاختر بحث آخر أو عودة إلى القائمة الرئيسية 🏠",
        'my_cars_header': "<b>🗂️ إعلاناتك: {count}</b>\n\n⬇️ عرض سياراتك...",
        'no_listings': "<b>🚫 ليس لديك إعلانات نشطة</b>\n\n🚗 أضف سيارة جديدة من القائمة!",
        'my_cars_end': "<b>✅ نهاية إعلاناتك</b>\n\n🏠 العودة إلى القائمة الرئيسية",
        'year_label': "📅 السنة:",
        'price_label': "💰 السعر:",
        'miles_label': "🛣️ الكيلومترات:",
        'location_label': "📍 الموقع:",
        'condition_label': "⭐ الحالة:",
        'phone_label': "📞 الهاتف:",
        'posted_label': "🕐 نشر في:",
        'contact_tip': "💡 اضغط على الأزرار أدناه للتواصل مع البائع",
        'manage_tip': "💡 إدارة إعلانك أدناه",
        'copy_phone': "📞 نسخ الهاتف",
        'message_seller': "✉️ رسالة للبائع",
        'delete': "🗑️ حذف",
        'yes_delete': "✅ نعم، حذف",
        'no_delete': "❌ لا",
        'phone_copied': "📞 <b>{phone}</b>\n\n✅ تم نسخ رقم الهاتف!\n💡 اضغط مطولاً للنسخ مرة أخرى",
        'deletion_cancelled': "❌ تم إلغاء الحذف",
        'listing_deleted': "✅ تم حذف الإعلان!",
        'delete_failed': "⚠️ تعذر الحذف - غير موجود أو ليس ملكك",
        'listing_deleted_caption': "🚫 تم حذف هذا الإعلان",
        'under_10k': "أقل من $10,000",
        'under_20k': "أقل من $20,000",
        'under_30k': "أقل من $30,000",
        'all_cars': "جميع السيارات",
        'language_changed': "<b>✅ تم تغيير اللغة إلى {lang}</b>",
        'choose_language': "<b>🌐 اختر لغتك / Choose Your Language / Choisissez votre langue</b>"
    },
    'fr': {
        'main_menu': [
            ["🚗 Ajouter Voiture", "🔍 Parcourir Voitures"],
            ["🗂️ Mes Voitures", "📊 Statistiques"],
            ["ℹ️ Aide", "🌐 Langue"]
        ],
        'cancel_menu': [
            ["❌ Annuler", "🏠 Menu Principal"]
        ],
        'explore_menu': [
            ["💵 Moins de $10K", "💰 Moins de $20K"],
            ["💎 Moins de $30K", "📋 Toutes les Voitures"],
            ["🏠 Menu Principal"]
        ],
        'welcome': "<b>🎉 Bienvenue sur le Marché des Voitures!</b>\n\n🚗 Votre plateforme parfaite pour acheter et vendre des voitures\n\n<b>Que voulez-vous faire?</b>\n• 🚗 <b>Ajouter Voiture</b> - Lister votre voiture à vendre\n• 🔍 <b>Parcourir Voitures</b> - Trouvez votre voiture parfaite\n• 🗂️ <b>Mes Voitures</b> - Voir et gérer vos annonces\n• 📊 <b>Statistiques</b> - Informations du marché\n• ℹ️ <b>Aide</b> - Guide d'utilisation\n• 🌐 <b>Langue</b> - Changer la langue\n\n💡 <b>Conseil:</b> Accédez aux commandes depuis le menu ci-dessous ou le bouton menu 📝",
        'help': "<b>📖 Guide d'Utilisation du Bot</b>\n\n<b>🚗 Pour ajouter une voiture:</b>\n1️⃣ Appuyez sur <b>Ajouter Voiture</b>\n2️⃣ Entrez les détails de la voiture étape par étape\n3️⃣ Envoyez une photo claire de la voiture\n\n<b>🔍 Pour trouver une voiture:</b>\n1️⃣ Appuyez sur <b>Parcourir Voitures</b>\n2️⃣ Choisissez votre gamme de prix\n3️⃣ Parcourez les résultats et contactez les vendeurs\n\n<b>🗂️ Pour gérer vos voitures:</b>\n1️⃣ Appuyez sur <b>Mes Voitures</b>\n2️⃣ Voir vos annonces\n3️⃣ Supprimez n'importe quelle annonce avec le bouton\n\n<b>💡 Conseils Importants:</b>\n• Utilisez le menu persistant ci-dessous\n• Annulez toute opération avec <b>Annuler</b>\n• Prix en Dollars US\n\n<b>🆘 Besoin d'aide?</b>\nContact: <b>jalalweez@gmail.com</b>",
        'stats': "<b>📊 Statistiques du Marché des Voitures</b>\n\n🚗 <b>Total Voitures:</b> <b>{total}</b>\n\n<b>Répartition des Prix:</b>\n💵 Moins de $10K: {under_10k} voitures\n💰 Moins de $20K: {under_20k} voitures\n💎 Moins de $30K: {under_30k} voitures\n\n📈 Marché actif et mis à jour quotidiennement!",
        'add_step1': "<b>🚘 Étape 1 sur 8</b>\n\nEntrez le modèle de la voiture:\n<i>Exemple: Toyota Corolla ou Honda Civic</i>",
        'add_step2': "<b>📅 Étape 2 sur 8</b>\n\nEntrez l'année de fabrication:\n<i>Exemple: 2020 ou 2018</i>",
        'add_step2_invalid_format': "<b>⚠️ Veuillez entrer une année valide (4 chiffres)</b>\n<i>Exemple: 2020</i>",
        'add_step2_invalid_range': "<b>⚠️ L'année doit être entre 1990 et 2025</b>",
        'add_step3': "<b>💰 Étape 3 sur 8</b>\n\nEntrez le prix en Dollars US:\n<i>Exemple: 15000 ou 25000</i>",
        'add_step3_invalid': "<b>⚠️ Veuillez entrer un numéro de prix valide</b>\n<i>Exemple: 15000 ou 25000</i>",
        'add_step4': "<b>🛣️ Étape 4 sur 8</b>\n\nEntrez le kilométrage:\n<i>Exemple: 45000 ou 120000</i>",
        'add_step4_invalid': "<b>⚠️ Veuillez entrer un numéro de kilométrage valide (0 ou positif)</b>\n<i>Exemple: 45000</i>",
        'add_step5': "<b>📍 Étape 5 sur 8</b>\n\nEntrez l'emplacement:\n<i>Exemple: Miami, FL ou New York, NY</i>",
        'add_step6': "<b>⭐ Étape 6 sur 8</b>\n\nEntrez l'évaluation de l'état (1-10):\n<i>Exemple: 8 pour bon état</i>",
        'add_step6_invalid': "<b>⚠️ Veuillez entrer une évaluation valide entre 1 et 10</b>\n<i>Exemple: 8</i>",
        'add_step7': "<b>📞 Étape 7 sur 8</b>\n\nEntrez le numéro de téléphone:\n<i>Exemple: +1-555-123-4567 ou 5551234567</i>",
        'add_step8': "<b>📸 Étape 8 sur 8 (Finale)</b>\n\nEnvoyez une photo claire de la voiture:\n• La photo doit être claire\n• Photo extérieure préférée\n• Évitez les photos floues",
        'add_image_invalid': "<b>⚠️ Aucune photo reçue!</b>\nVeuillez envoyer une photo 📸",
        'add_success': "<b>✅ Votre annonce est en ligne!</b>\n\n<b>🆔 ID de l'Annonce:</b> <code>{car_id}</code>\n<b>🚘 Modèle:</b> {model}\n<b>📅 Année:</b> {year}\n<b>💰 Prix:</b> ${price:,.0f}\n<b>🛣️ Kilométrage:</b> {miles:,}\n<b>📍 Emplacement:</b> {location}\n<b>⭐ État:</b> {condition}/10\n<b>📞 Téléphone:</b> <code>{phone}</code>\n\n🎉 Votre annonce est maintenant visible pour tout le monde!\n📱 Les acheteurs vous contacteront bientôt",
        'cancelled': "<b>❌ Opération annulée</b>\n\n🏠 Retour au menu principal",
        'explore': "<b>🔍 Parcourir les Voitures Disponibles</b>\n\nChoisissez votre gamme de prix:\n💵 Moins de $10K\n💰 Moins de $20K\n💎 Moins de $30K\n📋 Toutes les voitures",
        'results_header': "<b>🔍 Résultats de Recherche: {filter_name}</b>\n<b>📊 Résultats:</b> {count} voitures\n\n⬇️ Affichage des voitures...",
        'no_cars': "<b>🚫 Aucune voiture disponible</b>\n\n<b>Filtre:</b> {filter_name}\nEssayez un autre filtre ou listez votre voiture! 🚗",
        'end_results': "<b>✅ Fin des résultats</b>\n\nChoisissez une autre recherche ou retour au menu principal 🏠",
        'my_cars_header': "<b>🗂️ Vos Annonces: {count}</b>\n\n⬇️ Affichage de vos voitures...",
        'no_listings': "<b>🚫 Vous n'avez aucune annonce active</b>\n\n🚗 Ajoutez une nouvelle voiture depuis le menu!",
        'my_cars_end': "<b>✅ Fin de vos annonces</b>\n\n🏠 Retour au menu principal",
        'year_label': "📅 Année:",
        'price_label': "💰 Prix:",
        'miles_label': "🛣️ Kilométrage:",
        'location_label': "📍 Emplacement:",
        'condition_label': "⭐ État:",
        'phone_label': "📞 Téléphone:",
        'posted_label': "🕐 Posté:",
        'contact_tip': "💡 Appuyez sur les boutons ci-dessous pour contacter le vendeur",
        'manage_tip': "💡 Gérer votre annonce ci-dessous",
        'copy_phone': "📞 Copier Téléphone",
        'message_seller': "✉️ Message Vendeur",
        'delete': "🗑️ Supprimer",
        'yes_delete': "✅ Oui, Supprimer",
        'no_delete': "❌ Non",
        'phone_copied': "📞 <b>{phone}</b>\n\n✅ Téléphone copié dans le presse-papiers!\n💡 Appuyez longuement pour copier à nouveau",
        'deletion_cancelled': "❌ Suppression annulée",
        'listing_deleted': "✅ Annonce supprimée!",
        'delete_failed': "⚠️ Impossible de supprimer - non trouvée ou pas la vôtre",
        'listing_deleted_caption': "🚫 Cette annonce a été supprimée",
        'under_10k': "Moins de $10,000",
        'under_20k': "Moins de $20,000",
        'under_30k': "Moins de $30,000",
        'all_cars': "Toutes les Voitures",
        'language_changed': "<b>✅ Langue changée en {lang}</b>",
        'choose_language': "<b>🌐 Choisissez votre langue / Choose Your Language / اختر لغتك</b>"
    }
}