name: Docker Build & Scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 813010034876.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: telegram-bot
  IMAGE_TAG: ${{ github.sha }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # ---------------------------
      # 1️⃣ Checkout repository
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v4
      # ---------------------------
      # 2️⃣ Configure AWS credentials
      # ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-region: ${{ env.AWS_REGION }}
      # ---------------------------
      # 3️⃣ Log in to Amazon ECR
      # ---------------------------
      - name: Docker Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      # ---------------------------
      # 4️⃣ Build Docker image
      # ---------------------------
      - name: Build Docker image
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      # ---------------------------
      # 5️⃣ Scan Docker image with Trivy
      # ---------------------------
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.21.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      # ---------------------------
      # 6️⃣ Push Docker image to ECR
      # ---------------------------
      - name: Push Docker image to ECR
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      # ---------------------------
      # 7️⃣ (Optional) Run Checkov for Terraform
      # ---------------------------
      # Uncomment if you want IaC scanning
      # - name: Run Checkov for Terraform
      #   uses: bridgecrewio/checkov-action@master
      #   with:
      #     directory: ./terraform
      #     framework: terraform
